apiVersion: v1
data:
  STORAGE_BACKENDS: {{ .Values.STORAGE_BACKENDS }}
  AUTO_RUN: {{ .Values.AUTO_RUN | quote }}
  CONVERSATION_URL: {{ (first .Values.ingress.hosts).host }}
{{- if .Values.elasticsearch.enabled }}
  ES_EXT_URL: {{ .Values.elasticsearch.ES_EXT_URL | quote}}
  ES_URL: {{ .Values.elasticsearch.ES_URL | quote}}
  es_ca_certs: {{ .Values.elasticsearch.es_ca_certs | quote }}
  es_index: {{ .Values.elasticsearch.es_index }}
{{- end }}
{{- if .Values.FILE_STORAGE.enabled }}
  FS_INDEX: {{ .Values.FILE_STORAGE.FS_INDEX | quote }}
{{- end }}
{{- if .Values.GIT.enabled }}
  GIT_USER_EMAIL: {{ .Values.GIT.GIT_USER_EMAIL | quote}}
  GIT_USER_NAME: {{ .Values.GIT.GIT_USER_NAME | quote}}
{{- end }}
  LOG_LEVEL: {{ .Values.LOG_LEVEL | quote}}
  MAX_USER_INPUT_TOKENS: {{ .Values.openAI.MAX_USER_INPUT_TOKENS | quote }}
  SAVE_TOKEN_USE_SUMMARY: {{ .Values.openAI.SAVE_TOKEN_USE_SUMMARY | quote }}
  max_response_tokens: {{ .Values.openAI.max_response_tokens | quote}}
  model: {{ .Values.openAI.model }}
  temperature: {{ .Values.openAI.temperature | quote }}
  top_p: {{ .Values.openAI.top_p | quote }}
{{- if .Values.slack.enabled }}  
  slack_auth_url: {{ .Values.slack.slack_auth_url }}
  slack_post_url: {{ .Values.slack.slack_post_url }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ include "argonaut.fullname" . }}
  name: {{ include "argonaut.fullname" . }}
