apiVersion: v1
kind: Service
metadata:
  name: {{ include "argonaut.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "argonaut.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "argonaut.fullname" . }}
  ports:
  - name: http
    port: 80
    targetPort: 5000
